<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>d050c5e5-49e4-43ec-8e02-db8332d7605f</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>.</DockerfileContext>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="PracticeVaultAPI\**\*.cs" />
		<Content Remove="PracticeVaultAPI\**\*" />
		<EmbeddedResource Remove="PracticeVaultAPI\**\*" />
		<None Remove="PracticeVaultAPI\**\*" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
	</ItemGroup>

</Project>